[self]
judgeCapability = 4
name = "TestJudger"
port = 9900
host = "0.0.0.0"
trustIp = "127.0.0.1"
[language]
c = "/usr/bin/gcc"
cpp = "/usr/bin/g++"
python = "/usr/bin/python3"
java = "/usr/bin/java"
javac = "/usr/bin/javac"
node = "/usr/bin/node"
[judger]
docker = "/usr/bin/docker"
tmpdirBase = "/tmp/GP"
defaultPidLimit = 64
uid = 1999
gid = 1999
imageId = "e9b5fed0edb1"
compileMemoryLimit = 536870912
compileTimeLimit = 10000
fileLimit = 134217728
